---
- name: Post Installation PostgreSQL on Standby
  hosts: server2
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: Stop PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
    - name: Create PostgreSQL archive directory
      file:
        path: /var/lib/postgresql/16/main/archive
        state: directory
        owner: postgres
        group: postgres
        mode: '0770'

    - name: Remove all contents of PostgreSQL main directory
      become: yes
      command: rm -rf /var/lib/postgresql/16/main/

    - name: ADD to  pg_hba 
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "{{ item.line }}"
        create: yes
      loop:
        - { line: 'host    all             all             0.0.0.0/0               md5' }
        - { line: '#       user-name		                   standby-IP' }
        - { line: 'host    replication     replusr         {{ ip_server1 }}/32      trust' }

    - name: Run pg_basebackup as postgres user
      become: yes
      become_user: postgres
      command: pg_basebackup -R -h {{ ip_server1 }} -D /var/lib/postgresql/16/main -U replusr -P --wal-method=stream
      environment:
        PGPASSWORD: "1"  # If you need to pass the password for the replication user

    - name: Chown data directory
      become: yes
      command: chown -R postgres:postgres /var/lib/postgresql/16/main


    - name: Restart PostgreSQL
      become: yes
      service:
        name: postgresql
        state: restarted
