---
- name: Check Standby
  hosts: server2
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: Run pg_stat_wal_receiver
      become: yes
      become_user: postgres
      command: psql -x -c "select * from  pg_stat_wal_receiver;"
      register: query_output

    - name: Display query output
      debug:
        var: query_output.stdout
